In [98]:
import pandas as pd

In [107]:
bicimad = pd.read_csv('datasets/bicimad.csv')
bicimad

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,geometry_coordinates
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,"[-3.7018341, 40.4172137]"
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,"[-3.701602938060457, 40.41731271011562]"
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,"[-3.7058415, 40.4205886]"
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,"[-3.7069171, 40.4302937]"
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,"[-3.7025875, 40.4285524]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,266,Ciudad Universitaria 1,0,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,0,24,0,Point,"[-3.72699, 40.44375]"
260,267,Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,12,0,Point,"[-3.72693, 40.44342]"
261,268,Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,9,14,0,Point,"[-3.7272945, 40.4483322]"
262,269,Facultad Derecho,0,261,Avenida Complutense nº 23,1,0,24,5,18,0,Point,"[-3.72937, 40.45109]"
263,270,Zurbano,0,247,Calle Zurbano nº 90,1,0,24,6,15,0,Point,"[-3.69281, 40.43837]"

In [108]:
# new data frame with split value columns
bicimad_new = bicimad["geometry_coordinates"].str.split(",", n = 1, expand = True)
  
# making separate first name column from new data frame
bicimad["longitud"]= bicimad_new[0]
  
# making separate last name column from new data frame
bicimad["latitud"]= bicimad_new[1]
  
# Dropping old Name columns
bicimad.drop(columns =["geometry_coordinates"], inplace = True)
bicimad_new

                       0                    1
0            [-3.7018341          40.4172137]
1    [-3.701602938060457   40.41731271011562]
2            [-3.7058415          40.4205886]
3            [-3.7069171          40.4302937]
4            [-3.7025875          40.4285524]
..                   ...                  ...
259            [-3.72699            40.44375]
260            [-3.72693            40.44342]
261          [-3.7272945          40.4483322]
262            [-3.72937            40.45109]
263            [-3.69281            40.43837]

[264 rows x 2 columns]

In [109]:
bicimad['longitud'] = bicimad['longitud'].str.replace('[', '', regex=True)
bicimad['latitud'] = bicimad['latitud'].str.replace(']', '', regex=True)
bicimad

,id,name,light,number,address,activate,no_available,total_bases,dock_bikes,free_bases,reservations_count,geometry_type,longitud,latitud
0,1,Puerta del Sol A,2,1a,Puerta del Sol nº 1,1,0,30,15,11,0,Point,-3.7018341,40.4172137
1,2,Puerta del Sol B,1,1b,Puerta del Sol nº 1,1,0,30,22,4,0,Point,-3.701602938060457,40.41731271011562
2,3,Miguel Moya,2,2,Calle Miguel Moya nº 1,1,0,24,12,11,0,Point,-3.7058415,40.4205886
3,4,Plaza Conde Suchil,0,3,Plaza del Conde del Valle de Súchil nº 3,1,0,18,4,11,0,Point,-3.7069171,40.4302937
4,5,Malasaña,2,4,Calle Manuela Malasaña nº 5,1,0,24,12,12,0,Point,-3.7025875,40.4285524
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259,266,Ciudad Universitaria 1,0,258,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,0,24,0,Point,-3.72699,40.44375
260,267,Ciudad Universitaria 2,2,259,Avenida de la Complutense (Metro Ciudad Univer...,1,0,24,12,12,0,Point,-3.72693,40.44342
261,268,Facultad Biología,2,260,Calle José Antonio Novais frente al nº 12,1,0,24,9,14,0,Point,-3.7272945,40.4483322
262,269,Facultad Derecho,0,261,Avenida Complutense nº 23,1,0,24,5,18,0,Point,-3.72937,40.45109
263,270,Zurbano,0,247,Calle Zurbano nº 90,1,0,24,6,15,0,Point,-3.69281,40.43837

In [6]:
residentes = pd.read_csv('datasets/residentes.csv', sep=";")
residentes

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,13470,Aparcamiento mixto. Arquitecto Ribera,NaN,NaN,NaN,NaN,Plazas: 318 públicas y 298 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,BARCELO,...,CENTRO,440764,4475560,40.426688,-3.699617,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
1,59060,Aparcamiento mixto. Avenida de América (interc...,NaN,NaN,NaN,NaN,Información sobre accesibilidad: Tiene escale...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PRADENA DEL RINCON,...,CHAMARTIN,442725,4476896,40.438861,-3.676622,917 376 257,NaN,intercambiador@intercambiador.net,/contenido/entidadesYorganismos/AparcamientosR...,
2,5898885,Aparcamiento mixto. Avenida de Portugal,NaN,Horario de apertura de 6:00 h a 22:00 h los dí...,NaN,NaN,Plazas: 432 públicas y 437 para residentes In...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PORTUGAL,...,LATINA,437399,4473658,40.411180,-3.737832,917 877 292 (grúa municipal),NaN,aparcamientos@madridmovilidad.es,/contenido/entidadesYorganismos/AparcamientosR...,
3,13475,Aparcamiento mixto. Brasil,NaN,NaN,NaN,NaN,Plazas: 226 públicas y 400 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,GENERAL YAG&amp;Uuml;E,...,TETUAN,441255,4478822,40.456108,-3.694132,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
4,183747,Aparcamiento mixto. Casino de la Reina,NaN,NaN,NaN,NaN,Plazas: 135 públicas y 449 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CASINO,...,CENTRO,440213,4473147,40.406793,-3.704609,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
268,13611,Aparcamiento para residentes. Virgen del Puerto,NaN,NaN,NaN,NaN,Plazas: 793 Abierto 24 horas Titularidad: Ayu...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VIRGEN DEL PUERTO,...,ARGANZUELA,438940,4474102,40.413421,-3.720978,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
269,7397971,Aparcamiento para Residentes. Virgen del Romero,NaN,NaN,NaN,NaN,Plazas: 404 Abierto 24 horas Titularidad: Ayu...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VIRGEN DEL ROMERO,...,CIUDAD LINEAL,444874,4476868,40.438754,-3.651282,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
270,13614,Aparcamiento para residentes. Vista Alegre,NaN,NaN,NaN,NaN,Plazas: 402 Abierto 24 horas Titularidad: Ayu...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,MATILDE HERNANDEZ,...,CARABANCHEL,437489,4471080,40.386090,-3.737782,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
271,13493,Aparcamiento para residentes. Vital Aza,NaN,NaN,NaN,NaN,Plazas: 202 Abierto 24 horas Titularidad: Ayu...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VITAL AZA,...,CIUDAD LINEAL,445329,4475779,40.430857,-3.644542,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
272,13463,Aparcamiento público. Plaza de España,NaN,NaN,NaN,NaN,Plazas: 800 (hasta 535 abonados) Abierto 24 ho...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ESPA&amp;Ntilde;A,...,MONCLOA-ARAVACA,439631,4475032,40.423723,-3.711658,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,NaN

In [7]:
residentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 273 entries, 0 to 272
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PK                   273 non-null    int64
 1   NOMBRE               273 non-null    object
 2   DESCRIPCION-ENTIDAD  1 non-null      object
 3   HORARIO              2 non-null      object
 4   EQUIPAMIENTO         0 non-null      float64
 5   TRANSPORTE           0 non-null      float64
 6   DESCRIPCION          270 non-null    object
 7   ACCESIBILIDAD        273 non-null    int64
 8   CONTENT-URL          273 non-null    object
 9   NOMBRE-VIA           273 non-null    object
 10  CLASE-VIAL           273 non-null    object
 11  TIPO-NUM             270 non-null    object
 12  NUM                  268 non-null    object
 13  PLANTA               0 non-null      float64
 14  PUERTA               0 non-null      float64
 15  ESCALERAS            0 non-null      float64
 16  ORIENTACION          25 non-null     object
 17  LOCALIDAD            273 non-null    object
 18  PROVINCIA            273 non-null    object
 19  CODIGO-POSTAL        271 non-null    float64
 20  BARRIO               272 non-null    object
 21  DISTRITO             273 non-null    object
 22  COORDENADA-X         273 non-null    int64
 23  COORDENADA-Y         273 non-null    int64
 24  LATITUD              272 non-null    float64
 25  LONGITUD             272 non-null    float64
 26  TELEFONO             28 non-null     object
 27  FAX                  0 non-null      float64
 28  EMAIL                11 non-null     object
 29  TIPO                 273 non-null    object
 30  Unnamed: 30          272 non-null    object
dtypes: float64(9), int64(4), object(18)
memory usage: 66.2+ KB

In [8]:
residentes = residentes[residentes['NUM'].notna()]

In [9]:
residentes.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 268 entries, 0 to 272
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PK                   268 non-null    int64
 1   NOMBRE               268 non-null    object
 2   DESCRIPCION-ENTIDAD  1 non-null      object
 3   HORARIO              2 non-null      object
 4   EQUIPAMIENTO         0 non-null      float64
 5   TRANSPORTE           0 non-null      float64
 6   DESCRIPCION          265 non-null    object
 7   ACCESIBILIDAD        268 non-null    int64
 8   CONTENT-URL          268 non-null    object
 9   NOMBRE-VIA           268 non-null    object
 10  CLASE-VIAL           268 non-null    object
 11  TIPO-NUM             266 non-null    object
 12  NUM                  268 non-null    object
 13  PLANTA               0 non-null      float64
 14  PUERTA               0 non-null      float64
 15  ESCALERAS            0 non-null      float64
 16  ORIENTACION          25 non-null     object
 17  LOCALIDAD            268 non-null    object
 18  PROVINCIA            268 non-null    object
 19  CODIGO-POSTAL        266 non-null    float64
 20  BARRIO               267 non-null    object
 21  DISTRITO             268 non-null    object
 22  COORDENADA-X         268 non-null    int64
 23  COORDENADA-Y         268 non-null    int64
 24  LATITUD              267 non-null    float64
 25  LONGITUD             267 non-null    float64
 26  TELEFONO             27 non-null     object
 27  FAX                  0 non-null      float64
 28  EMAIL                10 non-null     object
 29  TIPO                 268 non-null    object
 30  Unnamed: 30          267 non-null    object
dtypes: float64(9), int64(4), object(18)
memory usage: 67.0+ KB

In [10]:
publicos_dis = pd.read_csv('datasets/publicos-dis.csv', sep=";")
publicos_dis.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,11483771,Aparcamiento disuasorio Aviación Española,NaN,Abierto 24 horas,NaN,Autobuses: EMT: Línea 17 (destino Pl. Ma...,"Plazas: para automóviles: 344 (de las cuales,...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,FUENTE DE LIMA,...,LATINA,4334.0,44706.0,40.383353,-3.783593,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
1,10489514,Aparcamiento disuasorio Estadio Metropolitano ...,NaN,Horario de apertura de 6:00 h a 22:00 h los dí...,NaN,NaN,Plazas: para automóviles: 1719 para motocicle...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,ARCENTALES,...,SAN BLAS-CANILLEJAS,448768.0,4476134.0,40.434154,-3.598831,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
2,11413444,Aparcamiento disuasorio Fuente de la Mora,NaN,Abierto 24 horas,NaN,Autobuses: EMT: 150 Cercanias: ...,"Plazas: para automóviles: 368 (de las cuales,...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,DULCE CHACON,...,HORTALEZA,NaN,NaN,40.484443,-3.664503,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
3,11544464,Aparcamiento disuasorio Islazul,NaN,NaN,NaN,Autobuses: EMT: SE Plaza Elíptica &amp;n...,Número de plazas: 224 plazas Código del aparc...,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CALDERILLA,...,CARABANCHEL,437347.0,4468555.0,40.365217,-3.737923,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
4,11413620,Aparcamiento disuasorio Pitis,NaN,Abierto 24 horas,NaN,"Autobuses: EMT: 64, 82 Cercanias: ...","Plazas: para automóviles: 402 (de las cuales,...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,GLORIA FUERTES,...,FUENCARRAL-EL PARDO,NaN,NaN,40.494193,-3.727236,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,

In [11]:
publicos_dis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61 entries, 0 to 60
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PK                   61 non-null     int64
 1   NOMBRE               61 non-null     object
 2   DESCRIPCION-ENTIDAD  1 non-null      object
 3   HORARIO              6 non-null      object
 4   EQUIPAMIENTO         0 non-null      float64
 5   TRANSPORTE           4 non-null      object
 6   DESCRIPCION          61 non-null     object
 7   ACCESIBILIDAD        61 non-null     int64
 8   CONTENT-URL          61 non-null     object
 9   NOMBRE-VIA           61 non-null     object
 10  CLASE-VIAL           61 non-null     object
 11  TIPO-NUM             61 non-null     object
 12  NUM                  57 non-null     float64
 13  PLANTA               0 non-null      float64
 14  PUERTA               0 non-null      float64
 15  ESCALERAS            0 non-null      float64
 16  ORIENTACION          1 non-null      object
 17  LOCALIDAD            61 non-null     object
 18  PROVINCIA            61 non-null     object
 19  CODIGO-POSTAL        61 non-null     int64
 20  BARRIO               61 non-null     object
 21  DISTRITO             61 non-null     object
 22  COORDENADA-X         59 non-null     float64
 23  COORDENADA-Y         59 non-null     float64
 24  LATITUD              61 non-null     float64
 25  LONGITUD             61 non-null     float64
 26  TELEFONO             19 non-null     object
 27  FAX                  0 non-null      float64
 28  EMAIL                10 non-null     object
 29  TIPO                 61 non-null     object
 30  Unnamed: 30          60 non-null     object
dtypes: float64(10), int64(3), object(18)
memory usage: 14.9+ KB

In [12]:
aparcamientos = pd.concat ([residentes, publicos_dis])
aparcamientos

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,13470,Aparcamiento mixto. Arquitecto Ribera,NaN,NaN,NaN,NaN,Plazas: 318 públicas y 298 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,BARCELO,...,CENTRO,440764.0,4475560.0,40.426688,-3.699617,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
1,59060,Aparcamiento mixto. Avenida de América (interc...,NaN,NaN,NaN,NaN,Información sobre accesibilidad: Tiene escale...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PRADENA DEL RINCON,...,CHAMARTIN,442725.0,4476896.0,40.438861,-3.676622,917 376 257,NaN,intercambiador@intercambiador.net,/contenido/entidadesYorganismos/AparcamientosR...,
2,5898885,Aparcamiento mixto. Avenida de Portugal,NaN,Horario de apertura de 6:00 h a 22:00 h los dí...,NaN,NaN,Plazas: 432 públicas y 437 para residentes In...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PORTUGAL,...,LATINA,437399.0,4473658.0,40.411180,-3.737832,917 877 292 (grúa municipal),NaN,aparcamientos@madridmovilidad.es,/contenido/entidadesYorganismos/AparcamientosR...,
3,13475,Aparcamiento mixto. Brasil,NaN,NaN,NaN,NaN,Plazas: 226 públicas y 400 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,GENERAL YAG&amp;Uuml;E,...,TETUAN,441255.0,4478822.0,40.456108,-3.694132,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
4,183747,Aparcamiento mixto. Casino de la Reina,NaN,NaN,NaN,NaN,Plazas: 135 públicas y 449 para residentes Abi...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CASINO,...,CENTRO,440213.0,4473147.0,40.406793,-3.704609,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosR...,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,13474,Aparcamiento público. Plaza del Rey,NaN,NaN,NaN,NaN,Plazas: 160 Información sobre accesibilidad: ...,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,REY,...,CENTRO,440967.0,4474629.0,40.420188,-3.695872,915 225 219,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
57,13456,Aparcamiento público. Santa Ana,NaN,NaN,NaN,NaN,Plazas: 325 Información sobre accesibilidad: ...,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,SANTA ANA,...,CENTRO,440536.0,4474042.0,40.414878,-3.700898,915 214 312,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
58,10737574,Aparcamiento público. Usera,NaN,NaN,NaN,NaN,Plazas: 36 Titularidad : Ayuntamiento de Madrid,0,http://www.madrid.es/sites/v/index.jsp?vgnextc...,AMPARO USERA,...,USERA,440032.0,4470962.0,40.387103,-3.706526,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
59,13468,Aparcamiento público. Velázquez - Juan Bravo,NaN,NaN,NaN,NaN,Plazas: 371 Abierto 24 horas Admite Tarjeta Bo...,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,VELAZQUEZ,...,SALAMANCA,442140.0,4476138.0,40.431992,-3.683450,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,
60,13453,Aparcamiento público. Villa de París,NaN,NaN,NaN,NaN,Plazas rotación: 169 Plazas motos: 2 Inform...,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,MARQUES DE LA ENSENADA,...,CENTRO,441263.0,4475173.0,40.425335,-3.692342,NaN,NaN,NaN,/contenido/entidadesYorganismos/AparcamientosP...,NaN

In [13]:
aparcamientos.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329 entries, 0 to 60
Data columns (total 31 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   PK                   329 non-null    int64
 1   NOMBRE               329 non-null    object
 2   DESCRIPCION-ENTIDAD  2 non-null      object
 3   HORARIO              8 non-null      object
 4   EQUIPAMIENTO         0 non-null      float64
 5   TRANSPORTE           4 non-null      object
 6   DESCRIPCION          326 non-null    object
 7   ACCESIBILIDAD        329 non-null    int64
 8   CONTENT-URL          329 non-null    object
 9   NOMBRE-VIA           329 non-null    object
 10  CLASE-VIAL           329 non-null    object
 11  TIPO-NUM             327 non-null    object
 12  NUM                  325 non-null    object
 13  PLANTA               0 non-null      float64
 14  PUERTA               0 non-null      float64
 15  ESCALERAS            0 non-null      float64
 16  ORIENTACION          26 non-null     object
 17  LOCALIDAD            329 non-null    object
 18  PROVINCIA            329 non-null    object
 19  CODIGO-POSTAL        327 non-null    float64
 20  BARRIO               328 non-null    object
 21  DISTRITO             329 non-null    object
 22  COORDENADA-X         327 non-null    float64
 23  COORDENADA-Y         327 non-null    float64
 24  LATITUD              328 non-null    float64
 25  LONGITUD             328 non-null    float64
 26  TELEFONO             46 non-null     object
 27  FAX                  0 non-null      float64
 28  EMAIL                20 non-null     object
 29  TIPO                 329 non-null    object
 30  Unnamed: 30          327 non-null    object
dtypes: float64(10), int64(2), object(19)
memory usage: 82.2+ KB

In [14]:
parks = aparcamientos.drop(aparcamientos.columns[[2, 3, 4, 5,6,7,8,11,13,14,15,16,22,23,26,27,28,29,30]], axis=1)
parks

,PK,NOMBRE,NOMBRE-VIA,CLASE-VIAL,NUM,LOCALIDAD,PROVINCIA,CODIGO-POSTAL,BARRIO,DISTRITO,LATITUD,LONGITUD
0,13470,Aparcamiento mixto. Arquitecto Ribera,BARCELO,CALLE,2,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.426688,-3.699617
1,59060,Aparcamiento mixto. Avenida de América (interc...,PRADENA DEL RINCON,CALLE,4,MADRID,MADRID,28002.0,PROSPERIDAD,CHAMARTIN,40.438861,-3.676622
2,5898885,Aparcamiento mixto. Avenida de Portugal,PORTUGAL,AVENIDA,155,MADRID,MADRID,28011.0,PUERTA DEL ANGEL,LATINA,40.411180,-3.737832
3,13475,Aparcamiento mixto. Brasil,GENERAL YAG&amp;Uuml;E,CALLE,11,MADRID,MADRID,28020.0,CUATRO CAMINOS,TETUAN,40.456108,-3.694132
4,183747,Aparcamiento mixto. Casino de la Reina,CASINO,CALLE,3,MADRID,MADRID,28005.0,EMBAJADORES,CENTRO,40.406793,-3.704609
...,...,...,...,...,...,...,...,...,...,...,...,...
56,13474,Aparcamiento público. Plaza del Rey,REY,PLAZA,1.0,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.420188,-3.695872
57,13456,Aparcamiento público. Santa Ana,SANTA ANA,PLAZA,16.0,MADRID,MADRID,28012.0,CORTES,CENTRO,40.414878,-3.700898
58,10737574,Aparcamiento público. Usera,AMPARO USERA,CALLE,46.0,MADRID,MADRID,28026.0,MOSCARDO,USERA,40.387103,-3.706526
59,13468,Aparcamiento público. Velázquez - Juan Bravo,VELAZQUEZ,CALLE,88.0,MADRID,MADRID,28006.0,CASTELLANA,SALAMANCA,40.431992,-3.683450
60,13453,Aparcamiento público. Villa de París,MARQUES DE LA ENSENADA,CALLE,1.0,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.425335,-3.692342

In [63]:
parks['NUM'] = parks['NUM'].replace(['24-B'],'24')
parks['NUM'] = parks['NUM'].replace(['10 C'],'10')
parks['NUM'] = parks['NUM'].replace(['74 B'],'74')
parks['NUM'] = parks['NUM'].replace(['6-B'],'6')
parks['NUM'] = parks['NUM'].replace(['10-B'],'10')
parks['NUM'] = parks['NUM'].replace(['25-B'],'25')
parks['NUM'] = parks['NUM'].replace(['3-B'],'3')
parks['NUM'] = parks['NUM'].replace(['14-B'],'14')
parks['NUM'] = parks['NUM'].replace(['64-B'],'64')
parks['NUM'] = parks['NUM'].replace(['61 - B'],'61')
parks['NUM'] = parks['NUM'].replace(['25 -B'],'25')
parks['NUM'] = parks['NUM'].replace(['6 - b'],'6')
parks['NUM'] = parks['NUM'].replace(['1-B'],'1')
parks['NUM'] = parks['NUM'].replace(['13-B'],'13')
parks['NUM'] = parks['NUM'].replace(['143-B'],'143')
parks['NUM'] = parks['NUM'].replace(['2-B'],'2')
parks['NUM'] = parks['NUM'].replace(['4-B'],'4')
parks['NUM'] = parks['NUM'].replace(['9-B'],'9')
parks['NUM'] = parks['NUM'].replace(['12-B'],'12')
parks['NUM'] = parks['NUM'].replace(['98-B'],'98')
parks['NUM'] = parks['NUM'].replace(['19-B'],'19')

In [77]:
parks["NUM"] = pd.to_numeric(parks["NUM"])

In [78]:
parks.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329 entries, 0 to 60
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             329 non-null    int64
 1   NOMBRE         329 non-null    object
 2   NOMBRE-VIA     329 non-null    object
 3   CLASE-VIAL     329 non-null    object
 4   NUM            325 non-null    float64
 5   LOCALIDAD      329 non-null    object
 6   PROVINCIA      329 non-null    object
 7   CODIGO-POSTAL  327 non-null    float64
 8   BARRIO         328 non-null    object
 9   DISTRITO       329 non-null    object
 10  LATITUD        328 non-null    float64
 11  LONGITUD       328 non-null    float64
 12  Place address  329 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 36.0+ KB

In [80]:
parks['NUM'] = parks['NUM'].fillna(0)

In [81]:
parks['NUM'] = parks['NUM'].astype(int)

In [88]:
parks['NOMBRE-VIA'] = parks['NOMBRE-VIA'].replace(['GENERAL YAG&amp;Uuml;E'],'GENERAL YAGUE')

In [89]:
parks["Place address"] = parks["CLASE-VIAL"] + " " + parks["NOMBRE-VIA"] + "," + " " + parks["NUM"].astype(str)
parks

,PK,NOMBRE,NOMBRE-VIA,CLASE-VIAL,NUM,LOCALIDAD,PROVINCIA,CODIGO-POSTAL,BARRIO,DISTRITO,LATITUD,LONGITUD,Place address
0,13470,Aparcamiento mixto. Arquitecto Ribera,BARCELO,CALLE,2,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.426688,-3.699617,"CALLE BARCELO, 2"
1,59060,Aparcamiento mixto. Avenida de América (interc...,PRADENA DEL RINCON,CALLE,4,MADRID,MADRID,28002.0,PROSPERIDAD,CHAMARTIN,40.438861,-3.676622,"CALLE PRADENA DEL RINCON, 4"
2,5898885,Aparcamiento mixto. Avenida de Portugal,PORTUGAL,AVENIDA,155,MADRID,MADRID,28011.0,PUERTA DEL ANGEL,LATINA,40.411180,-3.737832,"AVENIDA PORTUGAL, 155"
3,13475,Aparcamiento mixto. Brasil,GENERAL YAGUE,CALLE,11,MADRID,MADRID,28020.0,CUATRO CAMINOS,TETUAN,40.456108,-3.694132,"CALLE GENERAL YAGUE, 11"
4,183747,Aparcamiento mixto. Casino de la Reina,CASINO,CALLE,3,MADRID,MADRID,28005.0,EMBAJADORES,CENTRO,40.406793,-3.704609,"CALLE CASINO, 3"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,13474,Aparcamiento público. Plaza del Rey,REY,PLAZA,1,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.420188,-3.695872,"PLAZA REY, 1"
57,13456,Aparcamiento público. Santa Ana,SANTA ANA,PLAZA,16,MADRID,MADRID,28012.0,CORTES,CENTRO,40.414878,-3.700898,"PLAZA SANTA ANA, 16"
58,10737574,Aparcamiento público. Usera,AMPARO USERA,CALLE,46,MADRID,MADRID,28026.0,MOSCARDO,USERA,40.387103,-3.706526,"CALLE AMPARO USERA, 46"
59,13468,Aparcamiento público. Velázquez - Juan Bravo,VELAZQUEZ,CALLE,88,MADRID,MADRID,28006.0,CASTELLANA,SALAMANCA,40.431992,-3.683450,"CALLE VELAZQUEZ, 88"
60,13453,Aparcamiento público. Villa de París,MARQUES DE LA ENSENADA,CALLE,1,MADRID,MADRID,28004.0,JUSTICIA,CENTRO,40.425335,-3.692342,"CALLE MARQUES DE LA ENSENADA, 1"

In [91]:
parks = parks.drop(parks.columns[[2, 3, 4,]], axis=1)
parks

,PK,NOMBRE,BARRIO,DISTRITO,LATITUD,LONGITUD,Place address
0,13470,Aparcamiento mixto. Arquitecto Ribera,JUSTICIA,CENTRO,40.426688,-3.699617,"CALLE BARCELO, 2"
1,59060,Aparcamiento mixto. Avenida de América (interc...,PROSPERIDAD,CHAMARTIN,40.438861,-3.676622,"CALLE PRADENA DEL RINCON, 4"
2,5898885,Aparcamiento mixto. Avenida de Portugal,PUERTA DEL ANGEL,LATINA,40.411180,-3.737832,"AVENIDA PORTUGAL, 155"
3,13475,Aparcamiento mixto. Brasil,CUATRO CAMINOS,TETUAN,40.456108,-3.694132,"CALLE GENERAL YAGUE, 11"
4,183747,Aparcamiento mixto. Casino de la Reina,EMBAJADORES,CENTRO,40.406793,-3.704609,"CALLE CASINO, 3"
...,...,...,...,...,...,...,...
56,13474,Aparcamiento público. Plaza del Rey,JUSTICIA,CENTRO,40.420188,-3.695872,"PLAZA REY, 1"
57,13456,Aparcamiento público. Santa Ana,CORTES,CENTRO,40.414878,-3.700898,"PLAZA SANTA ANA, 16"
58,10737574,Aparcamiento público. Usera,MOSCARDO,USERA,40.387103,-3.706526,"CALLE AMPARO USERA, 46"
59,13468,Aparcamiento público. Velázquez - Juan Bravo,CASTELLANA,SALAMANCA,40.431992,-3.683450,"CALLE VELAZQUEZ, 88"
60,13453,Aparcamiento público. Villa de París,JUSTICIA,CENTRO,40.425335,-3.692342,"CALLE MARQUES DE LA ENSENADA, 1"

In [114]:
bicimad = bicimad.drop(bicimad.columns[[2, 3, 5, 6, 7, 8, 9, 10, 11,]], axis=1)
bicimad

,id,name,address,longitud,latitud
0,1,Puerta del Sol A,Puerta del Sol nº 1,-3.7018341,40.4172137
1,2,Puerta del Sol B,Puerta del Sol nº 1,-3.701602938060457,40.41731271011562
2,3,Miguel Moya,Calle Miguel Moya nº 1,-3.7058415,40.4205886
3,4,Plaza Conde Suchil,Plaza del Conde del Valle de Súchil nº 3,-3.7069171,40.4302937
4,5,Malasaña,Calle Manuela Malasaña nº 5,-3.7025875,40.4285524
...,...,...,...,...,...
259,266,Ciudad Universitaria 1,Avenida de la Complutense (Metro Ciudad Univer...,-3.72699,40.44375
260,267,Ciudad Universitaria 2,Avenida de la Complutense (Metro Ciudad Univer...,-3.72693,40.44342
261,268,Facultad Biología,Calle José Antonio Novais frente al nº 12,-3.7272945,40.4483322
262,269,Facultad Derecho,Avenida Complutense nº 23,-3.72937,40.45109
263,270,Zurbano,Calle Zurbano nº 90,-3.69281,40.43837

In [115]:
bicimad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        264 non-null    int64
 1   name      264 non-null    object
 2   address   264 non-null    object
 3   longitud  264 non-null    object
 4   latitud   264 non-null    object
dtypes: int64(1), object(4)
memory usage: 10.4+ KB

In [117]:
bicimadf = bicimad

In [120]:
bicimadf.to_csv('./datasets/bicimadf.csv', index = False)

In [121]:
parkings = parks

In [122]:
parkings.to_csv('./datasets/parkings.csv', index = False)